import { sourceNode } from "./utils";

export const stage2Nodes = [
  sourceNode({
    id: "stage2.overview.integrated-infrastructure",
    stage: 2,
    kind: "prose",
    lineStart: 589,
    lineEnd: 599,
    sectionTitle: "Overview",
  }),
  sourceNode({
    id: "stage2.overview.ai-pillar",
    stage: 2,
    kind: "prose",
    lineStart: 600,
    lineEnd: 615,
    sectionTitle: "Overview",
  }),
  sourceNode({
    id: "stage2.kpi.mass-to-orbit",
    stage: 2,
    kind: "kpi",
    lineStart: 774,
    lineEnd: 775,
    sectionTitle: "Our Unparalleled Launch Capabilities",
    kpi: { value: "7,400", unit: "metric tons", label: "mass to orbit", asOf: "2026-03-31" },
  }),
  sourceNode({
    id: "stage2.kpi.orbital-launches",
    stage: 2,
    kind: "kpi",
    lineStart: 775,
    lineEnd: 776,
    sectionTitle: "Our Unparalleled Launch Capabilities",
    kpi: { value: 650, label: "orbital launches", asOf: "2026-03-31" },
  }),
  sourceNode({
    id: "stage2.kpi.starlink-subscribers",
    stage: 2,
    kind: "kpi",
    lineStart: 640,
    lineEnd: 648,
    sectionTitle: "Overview",
    kpi: { value: "10.3", unit: "million", label: "Starlink Subscribers", asOf: "2026-03-31" },
  }),
  sourceNode({
    id: "stage2.milestone.2008.falcon-1",
    stage: 2,
    kind: "milestone",
    lineStart: 915,
    lineEnd: 915,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2008, label: "First private liquid-fuel rocket to reach orbit" },
  }),
  sourceNode({
    id: "stage2.milestone.2012.dragon-dock",
    stage: 2,
    kind: "milestone",
    lineStart: 916,
    lineEnd: 916,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2012, label: "First private spacecraft to dock with the ISS" },
  }),
  sourceNode({
    id: "stage2.milestone.2015-2017.reuse",
    stage: 2,
    kind: "milestone",
    lineStart: 917,
    lineEnd: 917,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2017, label: "Propulsive landing and orbital-class booster reflight" },
  }),
  sourceNode({
    id: "stage2.milestone.2019.leo-constellation",
    stage: 2,
    kind: "milestone",
    lineStart: 918,
    lineEnd: 918,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2019, label: "Large-scale LEO broadband satellite constellation" },
  }),
  sourceNode({
    id: "stage2.milestone.2020.crewed-flight",
    stage: 2,
    kind: "milestone",
    lineStart: 919,
    lineEnd: 920,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2020, label: "Private astronaut transport to orbit" },
  }),
  sourceNode({
    id: "stage2.milestone.2022.terminals",
    stage: 2,
    kind: "milestone",
    lineStart: 924,
    lineEnd: 924,
    sectionTitle: "Our Engineering-First Culture",
    milestone: { year: 2022, label: "Consumer-grade phased-array user terminals at scale" },
  }),
  sourceNode({
    id: "stage2.milestone.2025-2026.constellation-ai",
    stage: 2,
    kind: "milestone",
    lineStart: 925,
    lineEnd: 928,
    sectionTitle: "Our Engineering-First Culture",
    milestone: {
      year: 2026,
      label: "Satellite-to-mobile, gigawatt-scale AI, and orbital AI compute capability",
    },
  }),
];
