import { sourceNode } from "./utils";

export const stage3Nodes = [
  sourceNode({
    id: "stage3.space.summary",
    stage: 3,
    kind: "prose",
    lineStart: 627,
    lineEnd: 636,
    sectionTitle: "Overview",
  }),
  sourceNode({
    id: "stage3.space.vehicles",
    stage: 3,
    kind: "list",
    lineStart: 786,
    lineEnd: 808,
    sectionTitle: "Our Principal Launch Vehicles and Spacecraft",
  }),
  sourceNode({
    id: "stage3.space.business-detail",
    stage: 3,
    kind: "prose",
    lineStart: 4681,
    lineEnd: 4750,
    sectionTitle: "Business",
  }),
  sourceNode({
    id: "stage3.connectivity.summary",
    stage: 3,
    kind: "list",
    lineStart: 830,
    lineEnd: 858,
    sectionTitle: "Connectivity",
  }),
  sourceNode({
    id: "stage3.connectivity.business-detail",
    stage: 3,
    kind: "prose",
    lineStart: 4760,
    lineEnd: 4810,
    sectionTitle: "Business",
  }),
  sourceNode({
    id: "stage3.connectivity.starlink-mobile",
    stage: 3,
    kind: "prose",
    lineStart: 7709,
    lineEnd: 7791,
    sectionTitle: "Growth Strategies",
  }),
  sourceNode({
    id: "stage3.ai.summary",
    stage: 3,
    kind: "list",
    lineStart: 859,
    lineEnd: 898,
    sectionTitle: "AI",
  }),
  sourceNode({
    id: "stage3.ai.compute-advantage",
    stage: 3,
    kind: "prose",
    lineStart: 929,
    lineEnd: 1040,
    sectionTitle: "AI Compute Infrastructure",
  }),
  sourceNode({
    id: "stage3.ai.growth-strategies",
    stage: 3,
    kind: "prose",
    lineStart: 7792,
    lineEnd: 7932,
    sectionTitle: "Growth Strategies",
  }),
];
